name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android tools
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk aapt dx zipalign
        
    - name: Build APK
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: List build directory contents
      run: ls -la build/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZDSoftBypass-APK
        path: build/ZDSoftBypass-signed.apk
